### ISSUE TITLE
Unable to finetune official RWKV-5 models

### ISSUE THREAD

**Issue by General-Redshift** [RWKV/RWKV-infctx-trainer#16]
When attempting to finetune RWKV-5 world 0.1B from BlinkDL/rwkv-5-world, the following error occurs:

`RuntimeError: Error(s) in loading state_dict for RWKV:
	Missing key(s) in state_dict: "blocks.0.att.time_faaaa", "blocks.1.att.time_faaaa", "blocks.2.att.time_faaaa", "blocks.3.att.time_faaaa", "blocks.4.att.time_faaaa", "blocks.5.att.time_faaaa", "blocks.6.att.time_faaaa", "blocks.7.att.time_faaaa", "blocks.8.att.time_faaaa", "blocks.9.att.time_faaaa", "blocks.10.att.time_faaaa", "blocks.11.att.time_faaaa". 
	Unexpected key(s) in state_dict: "blocks.0.att.time_first", "blocks.1.att.time_first", "blocks.2.att.time_first", "blocks.3.att.time_first", "blocks.4.att.time_first", "blocks.5.att.time_first", "blocks.6.att.time_first", "blocks.7.att.time_first", "blocks.8.att.time_first", "blocks.9.att.time_first", "blocks.10.att.time_first", "blocks.11.att.time_first".`

**Comment by PicoCreator** [comment]
There been a slight change since the original 0.1B model - while blinks trainer is backward compatible to both formats, i only plan to support to finalised v5 format.

**Comment by General-Redshift** [comment]
Thanks for the quick reply
