### ISSUE TITLE
"\n" is escaped to "\\n" in preload_datapath.py 

### ISSUE THREAD

**Issue by cahya-wirawan** [RWKV/RWKV-infctx-trainer#34]
When we prepare dataset with preload_datapath.py, the newline `\n` in yaml configuration is escaped to  `\\n` which is not a newline anymore but two tokens `\\` and `n`.  The same with `\n\n` which is converted to `\\n\\n`. This is not correct in my opinion, because the (world) tokenizer will encode `\\n` as [93, 111] where `\n` is [11].
```
tokenizer.encode("\\n") == [93, 111]
tokenizer.encode("\\") == [93]
tokenizer.encode("n") == [111]
tokenizer.encode("\n") == [11]
```

**Comment by PicoCreator** [comment]
Thats wierd, can investigate further which settings in particular has this issue - is it the multi-column merge?

Cause im already using the \n as a token: https://github.com/RWKV/RWKV-infctx-trainer/blob/d97c2b94eadb34cb73b2e8b1fcfcf0e3e9c7b829/RWKV-v4neo/src/data.py#L362

**Comment by PicoCreator** [comment]
If its on the YAML side, i suspect we need to document this properly. Cause YAML does have options to properly escape (or not) these characters:
https://stackoverflow.com/a/22235064

**Comment by cahya-wirawan** [comment]
yes, the conversion is done by yaml.safe_load
