### ISSUE TITLE
[Feature request]Please eliminate CUDA dependency

### ISSUE THREAD

**Issue by yynil** [RWKV/RWKV-infctx-trainer#36]
Although CUDA ops accelerates training dramatically, other platform(Apple M2,AMD,Intel,Huawei, etc.) suffers from that. Please eliminate the CUDA dependency in the near future and accelerate training in a portable way(like vulcan). 
That means a lot to a lot of users, thanks a lot.

**Comment by PicoCreator** [comment]
Eliminating CUDA is one of the goals for the v5 implementation, which has been done.

Unfortunately the current pure pytorch is x100 slower then the cuda code, there is some experiments to speed that up, but that is a WIP

**Comment by PicoCreator** [comment]
Closing, as perf improvements to the pure pytorch impl is to be tracked seperately
