### ISSUE TITLE
[Need help] Implement BPTT cuda code for V5

### ISSUE THREAD

**Issue by PicoCreator** [RWKV/RWKV-infctx-trainer#64]
Currently the infctx trainer, does not build the gradiant for the state, when backpropping.

As such bptt_truncated is "enforced".

To fix this we need to port over the state gradient generation
- see example in v4 here: https://github.com/RWKV/RWKV-infctx-trainer/blob/42cf1af0ac18deef6d14f3cececc1f78989ceb88/RWKV-v4neo/cuda/wkv_cuda_bf16.cu#L144

To the current v5 cuda code
- somewhere here: https://github.com/RWKV/RWKV-infctx-trainer/blob/42cf1af0ac18deef6d14f3cececc1f78989ceb88/RWKV-v5/src/module/cuda/wkv5_cuda.cu#L339

Once this is supported, true "infctx" will be supported

**Comment by SmerkyG** [comment]
should work out of the box w/ the new nocuda code

**Comment by PicoCreator** [comment]
Works out of the box with the `RWKV_NO_CUDA=1` env variable flag now
