### ISSUE TITLE
dataload做了全核心数的num_workers是否有必要

### ISSUE THREAD

**Issue by diannaojiang** [RWKV/RWKV-infctx-trainer#7]
[dataload](https://github.com/RWKV/RWKV-infctx-trainer/blob/main/RWKV-v4neo/src/data.py#L479)做了全核心数的num_workers。8卡128核就是1000余进程，对磁盘读取限制、进程调度等都产生了影响，希望可以论证dataloader是否要设置一个最大合理值，降低性能开销。

**Comment by diannaojiang** [comment]
<img width="257" alt="image" src="https://github.com/RWKV/RWKV-infctx-trainer/assets/13410775/78a0982f-36e2-4e56-a079-3c7654d2e706">

**Comment by PicoCreator** [comment]
Hmm... would a param in dataload do to help limit this?
